version: '3'

services:
#  mongodb:
#    user: root
#    image: 'bitnami/mongodb:latest'
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./.mongodata:/bitnami
#    networks:
#      - my-net
#    environment:
#      - MONGODB_USERNAME=user
#      - MONGODB_PASSWORD=password123
#      - MONGODB_DATABASE=mongorun
#      - MONGODB_ROOT_PASSWORD=password123
#      - MONGODB_AUTH_DATABASE=mongorun
#    restart: 'no'
#
#  redis:
#    image: 'bitnami/redis:latest'
#    ports:
#      - '6379:6379'
#    networks:
#      - my-net
#    volumes:
#      - ./.persistent_data/redis-data:/bitnami
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes

  career_transformer:
    image: 'campus-career-transformer'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-net
#    depends_on:
#      - redis
#      - mongodb
    environment:
      - importer_id=5e4a4cf4234c6b2ec6f30e7e
      - ENV=stage
      - KOMBU_HOST=redis://redis:6379/
      - KOMBU_EXCHANGE=events-exchange
      - KOMBU_QUEUE=events-q-dev-stage
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=mongorun
      - MONGODB_AUTH_DATABASE=mongorun

networks:
  my-net:
    driver: bridge
